---
title: Spines
author: 
date: 2015-09-22
output:
  html_document:
    toc: true
---

```{r, message=FALSE, warning=FALSE}
library(DendriticSpineR)

spines <- read_spines(file = "kolce dendrytyczne myszy tg3-gm.csv",
                      animal_col_name = "Animal",
                      group_col_name = "Group",
                      photo_col_name = "Photo_ID_rel",
                      spines_col_name = "spine_number",
                      properties_col_name = c("length", "area", "length_area_ratio", "length_width_ratio"),
                      header = TRUE, sep = ";")
```

# length 

```{r}
plot_distributions(spines, property = "length", ecdf = TRUE, x_lim = c(0, 2))
plot_distributions(spines, property = "length", ecdf = FALSE, x_lim = c(0, 2))

plot_animals(spines, property = "length", box = FALSE)
plot_animals(spines, property = "length", box = TRUE)

plot_crossed_effects(spines, property = "length", strat = "Animal:group", mixed = TRUE)

(ms <- model_spines(spines, photo_col_name = "Photo_ID_rel"))
diffogram(ms)
```

# area 

```{r}
plot_distributions(spines, property = "area", ecdf = TRUE, x_lim = c(0, 2))
plot_distributions(spines, property = "area", ecdf = FALSE, x_lim = c(0, 2))

plot_animals(spines, property = "area", box = FALSE)
plot_animals(spines, property = "area", box = TRUE)

plot_crossed_effects(spines, property = "area", strat = "Animal:group", mixed = TRUE)

(ms <- model_spines(spines, photo_col_name = "Photo_ID_rel"))
diffogram(ms)
```

# length_area_ratio 

```{r}
plot_distributions(spines, property = "length_area_ratio", ecdf = TRUE, x_lim = c(0, 2))
plot_distributions(spines, property = "length_area_ratio", ecdf = FALSE, x_lim = c(0, 2))

plot_animals(spines, property = "length_area_ratio", box = FALSE)
plot_animals(spines, property = "length_area_ratio", box = TRUE)

plot_crossed_effects(spines, property = "length_area_ratio", strat = "Animal:group", mixed = TRUE)

(ms <- model_spines(spines, photo_col_name = "Photo_ID_rel"))
diffogram(ms)
```

# length_width_ratio 

```{r}
plot_distributions(spines, property = "length_width_ratio", ecdf = TRUE, x_lim = c(0, 2))
plot_distributions(spines, property = "length_width_ratio", ecdf = FALSE, x_lim = c(0, 2))

plot_animals(spines, property = "length_width_ratio", box = FALSE)
plot_animals(spines, property = "length_width_ratio", box = TRUE)

plot_crossed_effects(spines, property = "length_width_ratio", strat = "Animal:group", mixed = TRUE)

(ms <- model_spines(spines, photo_col_name = "Photo_ID_rel"))
diffogram(ms)
```

